apiVersion: apps/v1
kind: Deployment
metadata:
  name: positions-deployment
  labels:
    app: positions
spec:
  replicas: 1
  selector:
    matchLabels:
      app: positions
  template:
    metadata:
      labels:
        app: positions
    spec:
      containers:
        - name: positions
          image: positions:latest
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"
          ports:
            - containerPort: 3000
